version: "3.8"
services:
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: djangoapp
    build:
      context: ./mainProject
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mainProject:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0930d30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1

  celery:
    build:
      context: ./mainProject
    command: celery --app=mainProject worker -l INFO
    volumes:
      - ./mainProject:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=0930d30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
